version: '3'
services:
  redis:
    image: redis
    networks:
      - back-end  
    
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/var/lib/postgresql/data*
    networks:
      - back-end  

  vote:
    build: ./vote
    depends_on:
      - redis
    ports:
      - 5000:80
    networks:
      - front-end
      - back-end

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-end

  result:
    build: ./result
    depends_on:
      - db
    ports:
      - 5001:80
    networks:
      - front-end
      - back-end  

volumes:
  db-data:

networks:
  front-end:
  back-end:

